"""Obsolete this approach is slow and has so many junks code."""
from fpdf import FPDF
from fpdf.enums import XPos, YPos

pdf = FPDF()
pdf.add_page()
pdf.set_font('helvetica', 'B', size=23)
pdf.cell(0, 15, "Liquidity Discovery Weekly Analysis #2", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', '', size=16)
pdf.cell(0, 10, "Universal Assets Arbitrage Strategy: Cross-DEX Opportunities", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.image("img/1-click-arb-agent.png", x=10, y=None, w=100)
pdf.set_font('helvetica', 'B', size=17)
pdf.cell(0, 10, "The Cross-DEX Arbitrage Opportunity in 1-click", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', 'B', size=13)
pdf.cell(0, 10, "Background", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', '', size=11)
pdf.multi_cell(0, 6, "Vaporfund had been running crypto business for two years but always felt one step behind the market. After months of research, she discovered a pattern in the pricing of Universal's tokenized assets across different DEXs.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.cell(0, 10, "Arbi wallet:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

pdf.set_font('helvetica', 'U', size=11)
pdf.set_text_color(0, 0, 255)
pdf.cell(0, 10, "https://basescan.org/address/0xbd392784638d10a6cef2193e32edbd658739f4af#tokentxns", link="https://basescan.org/address/0xbd392784638d10a6cef2193e32edbd658739f4af#tokentxns", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_text_color(0, 0, 0)
pdf.set_font('helvetica', 'B', size=13)
pdf.cell(0, 10, "The Discovery", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', '', size=11)
pdf.multi_cell(0, 6, "On a quiet Friday afternoon in May 2025, Arbi noticed something peculiar. While monitoring prices of uSOL across multiple exchanges, he spotted a consistent price discrepancy:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.cell(0, 10, "   - On Kyberswap (Base network): uSOL trading at $165.23", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.cell(0, 10, "   - On Universal Assets DEX: uSOL trading at $163.57", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', '', size=11)
pdf.set_text_color(0, 0, 0)
pdf.cell(20, 10, "   - Buy tx:", new_x=XPos.RIGHT, new_y=YPos.LAST)
pdf.set_text_color(0, 0, 255)
pdf.cell(0, 10, "https://basescan.org/tx/0xc596528089f668befde8a1e08567117c6cdb049e2ec04da2173d68580d629a0f", link="https://basescan.org/tx/0xc596528089f668befde8a1e08567117c6cdb049e2ec04da2173d68580d629a0f", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_text_color(0, 0, 0)
pdf.cell(20, 10, "   - Sell tx:", new_x=XPos.RIGHT, new_y=YPos.LAST)
pdf.set_text_color(0, 0, 255)
pdf.cell(0, 10, "https://basescan.org/tx/0x5e7e54fa8fc4d78f8da2b8114d5ebdf28516252847424f5e90ac7ecf23b570cb", link="https://basescan.org/tx/0x5e7e54fa8fc4d78f8da2b8114d5ebdf28516252847424f5e90ac7ecf23b570cb", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_text_color(0, 0, 0)
pdf.cell(0, 10, "   - Result: +$1.5 (Profit)", new_x=XPos.RIGHT, new_y=YPos.LAST)
pdf.cell(0, 10, "", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.multi_cell(190, 6, "The differences might seem minimal to casual traders, but to Arbi, they represented a clear arbitrage opportunity.\nWith uSOL's high trading volume and relatively deep liquidity, these small percentage differences could translate to meaningful profits when executed at scale.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

pdf.set_font('helvetica', 'B', size=13)
pdf.cell(0, 10, "Setting Up the Strategy", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', '', size=11)
pdf.cell(0, 10, "Arbi's approach was methodical:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', style='B', size=11)
pdf.cell(0, 10, "1. Infrastructure Setup:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', style='', size=11)
pdf.cell(0, 10, "   He configured a 1-click arbitrage application at", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_text_color(0, 0, 255)
pdf.cell(0, 10, "   https://arbi.vaporfund.com/", link="https://arbi.vaporfund.com/", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', 'B', size=11)
pdf.set_text_color(0, 0, 0)
pdf.cell(0, 10, "2. Auto-check setting:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', '', size=11)
pdf.cell(0, 10, "   Arbi use this setting for checking arbitrage opportunities", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.cell(0, 10, "       - Input amount: 1000 USDC", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.cell(0, 10, "       - Minimum profit threshold: 1.0%", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.cell(0, 10, "       - Slippage Tolerance: 0.1%", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', style='B', size=11)
pdf.cell(0, 10, "3. Monitoring System:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', '', size=11)
pdf.multi_cell(0, 10, "   He developed a simple bot that monitored price discrepancies between the two exchanges, triggering alerts when spreads exceeded 1.0%.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', style='B', size=11)
pdf.cell(0, 10, "4. Gas Optimization:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', '', size=11)
pdf.multi_cell(0, 10, "Arbi created a gas strategy that adjusted based on network congestion, ensuring transactions would go through during profitable windows without overpaying.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

pdf.set_font('helvetica', style='B', size=13)
pdf.cell(0, 10, "The First Trade", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
pdf.set_font('helvetica', style='', size=11)
pdf.multi_cell(0, 10, "The opportunity came faster than expected. On Monday morning, Arbi's alert system pinged-uSEI was trading 1.2% lower on Universal Assets DEX compared to Kyberswap.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

pdf.set_font('helvetica', style='B', size=11)
pdf.cell(0, 10, "Trade Execution:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

# Add image for trade execution
pdf.image('img/trade_execution.png', x=None, y=None, w=100)

pdf.set_font('helvetica', style='', size=11)
pdf.multi_cell(0, 10, "For her $300 position, the profit after gas and slippage came to approximately $1.23 return in less than 10 minutes.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)




pdf.output("hello_report.pdf")
